version: '2.4'
volumes: { prometheus-data: {}, grafana-data: {} }
services:
  prometheus:
    image: quay.io/prometheus/prometheus
    container_name: gpu-prometheus
    volumes:
    - prometheus-data:/prometheus
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: host
    #ports:
    #  - "9090:9090"
    restart: unless-stopped  
  grafana:
    image: grafana/grafana
    container_name: gpu-grafana
    network_mode: host
    #ports:
    #  - "3001:3000"
    restart: unless-stopped
